apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-devops
  template:
    metadata:
      labels:
        app: api-devops
    spec:
      containers:
      - name: api
        image: api-devops:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017"